version: '3'

services:
  db:
    image: postgres:12.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres  # Update this line
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: restaurant_discovery_api_production


  web:
    build: .
    command: bash -c "entrypoint.sh rails s -b '0.0.0.0'"
    volumes:
      - ".:/app"
    environment:
      DB_URL: postgres://postgres:postgres@db
      PGUSER: postgres
      PGPASSWORD: postgres
    ports:
      - "3000:3000"


volumes:
  postgres_data:
