# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DB_URL'] %>
  
development:
  <<: *default
  database: restaurant_discovery_api_development

test:
  <<: *default
  database: restaurant_discovery_api_test

production:
  <<: *default
  database: restaurant_discovery_api_production
